web/config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  resource :account, only: [ :show ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  namespace :authentications do
    resources :events, only: :index
  end
  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  root "home#index"

  resources :bands, only: [ :show ] do
    resources :years, only: [ :show ], param: :year
  end

  resources :performances, only: [ :show ]
  resources :recordings, only: [ :show ]

  get "/.well-known/apple-app-site-association",
      to: "apple_app_site_association#index"

  namespace :admin do
    root to: "bands#index"

    resources :bands
  end

  namespace :api do
    resources :bands, only: [ :index ] do
      resources :top_performances, only: [ :index ]
      resources :years, only: [ :show ], param: :year
    end

    resources :performances, only: [ :show ]
    resources :recordings, only: [ :show ], id: /.*/
    resources :legacy_recordings, only: [ :show ], param: :identifier
  end

  scope :api do
    scope :legacy do
      get "/bands", to: "api/legacy/bands#index", as: :api_legacy_bands
      get "/bands/:collection/performances/top",
          to: "api/legacy/performances#top",
          as: :api_legacy_band_top_performances,
          collection: /.*/
      get "/bands/:collection/performances/on_this_day",
          to: "api/legacy/performances#top",
          as: :api_legacy_band_on_this_day_performances,
          collection: /.*/
      get "/bands/:collection/performances",
          to: "api/legacy/performances#index",
          as: :api_legacy_band_performances,
          collection: /.*/
      get "/bands/:collection/performances/:date/recordings",
          to: "api/legacy/recordings#index",
          as: :api_legacy_performance_recordings,
          collection: /.*/
      get "/recordings/:identifier/tracks",
          to: "api/legacy/tracks#index",
          as: :api_legacy_recording_tracks,
          identifier: /.*/
    end
  end
end

web/app/models/year.rb
class Year
  attr_reader :band, :year

  def initialize(band:, year:)
    @band = band
    @year = year
  end

  def to_param
    year
  end

  def top_performances(number = 5)
    performances.sort_by(&:num_stars).reverse[...number]
  end

  def performances
    @performances ||= band
      .performances
      .with_recording_metadata
      .in_year(year.to_i)
  end
end

web/app/controllers/api/years_controller.rb
# frozen_string_literal: true

module Api
  class YearsController < ApiController
    def show
      band = Band.find(params[:band_id])
      year = Year.new(band:, year: params[:year])
      render json: PerformanceBlueprint.render(year.performances, view: :with_metadata)
    end
  end
end

web/app/controllers/years_controller.rb
class YearsController < ApplicationController
  def show
    # @band = Band.find(params[:band_id])
    # @year = Year.new(band: @band, year: params[:year].to_i)

    render "welcome/index", layout: "application"
  end
end

web/app/helpers/years_helper.rb
module YearsHelper
end

web/app/views/years/show.html.erb
<%= render partial: 'shared/nav' %>

<div class="browse">
  <section class="browse__band_list">
    <h4>Choose a band</h4>
    <ul>
      <% Band.all.order(name: :asc).each do |band| %>
        <li>
          <%= link_to band.name, band_path(band) %>
        </li>
      <% end %>
    </ul>
  </section>

  <section class="browse__show_list">
    <div><%= link_to "< Back to top shows", band_path(@band) %></div>
    <h4><%= @band.name %>: <%= @year.year %></h4>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Venue</th>
          <th>Location</th>
          <th>Num. Recordings</th>
          <th>Avg. Rating</th>
        </tr>
      </thead>
      <tbody>
        <% @year.performances.each do |performance| %>
          <tr>
            <td class="browse__show_list__date"><%= link_to performance.date, performance_path(performance) %></td>
            <td><%= performance.venue %></td>
            <td><%= performance.city %>, <%= performance.state %></td>
            <td><%= performance.recordings.length %></td>
            <td><%= performance.num_stars.zero? ? '--' : performance.avg_rating %> / 5</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
</div>